[base]
env_name = boxoban

[vec]
total_agents = 2048
num_buffers = 4
num_threads = 1

[env]
num_agents = 1
difficulty = 2
int_r_coeff = 0.25
target_loss_pen_coeff = 0
max_steps = 150

[policy]
hidden_size = 64
num_layers = 2

[train]
gpus = 1
seed = 42
total_timesteps = 40_000_000
# learning_rate = 0.00134234
# anneal_lr = 1
# min_lr_ratio = 0.37872
# gamma = 0.989717
# gae_lambda = 0.759273
# replay_ratio = 1.6234
# clip_coef = 0.01
# vf_coef = 5
# vf_clip_coef = 5
# max_grad_norm = 1.20325
# ent_coef = 0.000188411
# momentum = 0.995526
# minibatch_size = 32768
# horizon = 64
# vtrace_rho_clip = 3.13347
# vtrace_c_clip = 2.75328
# prio_alpha = 0.453827
# prio_beta0 = 0.765589

[sweep.train.total_timesteps]
distribution = log_normal
min = 3e7
max = 1e9
scale = time

[sweep.policy.hidden_size]
distribution = uniform_pow2
min = 32
max = 1024
scale = auto

[sweep.policy.num_layers]
distribution = int_uniform
min = 1
max = 3
scale = auto

[sweep.vec.total_agents]
distribution = uniform_pow2
min = 256
max = 16384
scale = auto

[sweep.vec.num_buffers]
distribution = uniform_pow2
min = 1
max = 8
scale = auto

[sweep.train.horizon]
distribution = uniform_pow2
min = 16
max = 128
scale = auto

[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 4096
max = 65536
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
max = 0.1
scale = 0.5

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
max = 0.2
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
max = 0.9999
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.2
max = 0.995
scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.replay_ratio]
distribution = uniform
min = 0.25
max = 4.0
scale = auto

[sweep.train.clip_coef]
distribution = uniform
# Lower clip is sometimes better but less stable
min = 0.01
max = 1.0
scale = auto

# Optimal vf clip can be lower than 0.1,
# but this results in jank unstable runs
[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.01
max = 5.0
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.momentum]
distribution = logit_normal
min = 0.5
max = 0.999
scale = auto

[sweep.train.beta2]
distribution = logit_normal
min = 0.9
max = 0.99999
scale = auto

; [sweep.train.eps]
; distribution = log_normal
; min = 1e-14
; max = 1e-4
; scale = auto

[sweep.train.prio_alpha]
distribution = uniform 
min = 0.0
max = 1.0
scale = auto

[sweep.train.prio_beta0]
distribution = uniform 
min = 0.0
max = 1.0
scale = auto
