[base]
env_name = breakout
async = 1

[vec]
total_agents = 4096
num_buffers = 1
num_threads = 8
gpu_env = 1
num_policies = 1

[policy]
num_layers = 4
hidden_size = 32

[env]
num_agents = 1
frameskip = 3
width = 576
height = 330
initial_paddle_width = 62
paddle_width = 62
paddle_height = 8
ball_width = 32
ball_height = 32
brick_width = 32
brick_height = 12
brick_rows = 6
brick_cols = 18
initial_ball_speed = 256
max_ball_speed = 448
paddle_speed = 620
continuous = 0


# [train]
# gpus = 1
# seed = 42
# total_timesteps = 30000006
# learning_rate = 0.015
# anneal_lr = 1
# min_lr_ratio = 0.0
# gamma = 0.995
# gae_lambda = 0.9
# replay_ratio = 1.57860792
# clip_coef = 0.287249029
# vf_coef = 2
# vf_clip_coef = 0.01
# max_grad_norm = 1.40783215
# ent_coef = 0.00190271565
# anneal_ent_coef = 0
# min_ent_coef_ratio = 0.1
# momentum = 0.938853085
# beta1 = 0.95
# beta2 = 0.9
# eps = 1e-12
# minibatch_size = 8192
# horizon = 32
# vtrace_rho_clip = 1.0
# vtrace_c_clip = 1.0
# prio_alpha = 0.8
# prio_beta0 = 0.261975825

[train]
total_timesteps = 43_689_963
; learning_rate = 0.0627130643
; gamma = 0.96761483
; gae_lambda = 0.982877254
; replay_ratio = 1.88528275
; clip_coef = 0.81228894
; vf_coef = 3.46657705
; vf_clip_coef = 4.97819614
; max_grad_norm = 1.10759413
; ent_coef = 0.00489364704
; momentum = 0.869982362
; beta2 = 0.95
; minibatch_size = 65536
; horizon = 32
; prio_alpha = 0
; prio_beta0 = 0.534311116
; vtrace_c_clip = 1.0
; vtrace_rho_clip = 1.0

[sweep]
metric = score
downsample = 5

[sweep.train.total_timesteps]
distribution = log_normal
min = 3e7
max = 2e8
scale = auto

[sweep.env.frameskip]
distribution = int_uniform
min = 1
max = 8
mean = 4
scale = 2.0

[sweep.policy.hidden_size]
distribution = uniform_pow2
min = 32
max = 128
scale = auto

[sweep.policy.num_layers]
distribution = int_uniform
min = 1
max = 4
scale = auto

[sweep.vec.total_agents]
distribution = uniform_pow2
min = 256
max = 16384
scale = auto

; [sweep.vec.num_buffers]
; distribution = uniform_pow2
; min = 1
; max = 8
; scale = auto

[sweep.train.horizon]
distribution = uniform_pow2
min = 16
max = 128
scale = auto

[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 4096
max = 65536
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
max = 0.1
scale = 0.5

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
max = 0.2
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
max = 0.9999
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.2
max = 0.995
scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.replay_ratio]
distribution = uniform
min = 0.25
max = 4.0
scale = auto

[sweep.train.clip_coef]
distribution = uniform
# Lower clip is sometimes better but less stable
min = 0.01
max = 1.0
scale = auto

# Optimal vf clip can be lower than 0.1,
# but this results in jank unstable runs
[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.01
max = 5.0
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.momentum]
distribution = logit_normal
min = 0.5
max = 0.999
scale = auto

[sweep.train.beta2]
distribution = logit_normal
min = 0.9
max = 0.99999
scale = auto

; [sweep.train.eps]
; distribution = log_normal
; min = 1e-14
; max = 1e-4
; scale = auto
